FROM ubuntu:20.04

RUN apt-get update && \
    apt-get install -y \
        gcc \
        g++ \
        cmake \
        libpam-dev \
        libcurl4-openssl-dev \
        apt install libboost-dev \
        pamtester \
        rsyslog && \
    apt-get clean

ADD sram /etc/pam.d/sram

