FROM ubuntu:20.04

RUN apt-get update && \
    apt-get install -y \
        gcc \
        g++ \
        cmake \
        libpam-dev \
        libcurl4-gnutls-dev \
        libboost-dev \
        pamtester \
        rsyslog && \
    apt-get clean

ADD docker/sram /etc/pam.d/sram

